### ISSUE TITLE
Ability to add multiple coordinate systems

### ISSUE THREAD

**Issue by nattomi** [markummitchell/engauge6#2]
A useful feature would be the ability to define more coordinate systems with the Axis tool. Those coordinate systems would be named and each curve could be mapped to one of the coordinate systems. See http://www.largeimages.bgs.ac.uk/iip/magnetograms.html?id=410000/411882 for an example when such a feature would be extremely useful!

**Comment by markummitchell** [comment]
Sorry, but I could not figure out how to implement this with a LOT of work.  Besides a new control in the GUI to switch axes, there would also be various other GUI changes in Curve Settings, Coordinate Settings, and maybe elsewhere. Then, underneath there would be changes in many places to associate objects with the relevant set of axes. These changes underneath would spread to code everywhere, including the external python scripts. I am wondering if it is enough to just handle each axes in an image with a separate DIG file. As of a couple of days ago, multiple Engauge instances start up when multiple files are dragged onto the executable (one instance per file). So, one could drag all of the DIG files for one image into Engauge.

**Comment by markummitchell** [comment]
Hello, I don't know if you are still around, but I think I have a fix that will work without making the code or user interface very complicated. I wanted to check with anybody who was interested to see if this fix seems reasonable.

From the user point of view, there would be a new toolbar with a new widget - a dropdown listbox listing 'Coordinate System 1', 'Coordinate System 2' and so on up to the number of coordinate systems currently in effect. Initially, and usually, this widget would be disabled since there would only be one coordinate system, which should hopefully be ignored the majority of users who only need one coordinate system. There would also be a new menu entry under the Settings menu for adding/removing coordinate systems.

From a programming point of view, this could be implemented painlessly if the command stack was specific to each document (my big insight). 

Suggestions?

**Comment by nattomi** [comment]
Hi, Sorry for not being active lately. What you described in your last comment seems perfect for me. It is exactly how I imagined such a feature. In the XML project files then there could be something like a <CurvesAxes> node (with children like <Curve CurveName="Axes1">, <Curve CurveName="Axes2">, etc.) as well on the same level where the <CurvesGraphs> node takes place. Thank you again for all your efforts and also for mentioning me in the contributors section!

**Comment by Wastus** [comment]
I came across one of those diagrams today as well, solved it with two files. But the solution you are suggesting sounds nice and if you can implement it easily, that'd be nice for all.

How would you map a curve to a coordinate system though?

You could enhance the Axis Point Tool, so that it asks if you want to create another coordinate system if you try to place a fourth point (could get annoying though, and if the other enhancement gets implemented (with 4 points to define axis with unknown values) things get more complicated).

**Comment by nattomi** [comment]
@Wastus "How would you map a curve to a coordinate system though?" -- one possibility is to do it in the Curve Settings dialog. There are already sevaral selectors there so it's just a matter of adding one more.

**Comment by markummitchell** [comment]
At this point (subject to change) it appears that a whole new 'Coordinate System layer' would be added to the application. A new dialog would be added to let users add/remove a Coordinate System. All other layers (Axis curves, Graph curves) would belong to a specific Coordinate System, and the user selects the single active Coordinate System using a new dropdown list. This approach promises to be the easiest to understand (without any confusing complicated interactions). A disadvantage is that since only one Coordinate System, and its associated axis/graph  curves, appear at a time that the user cannot see all coordinate system and their axis/graph curves simultaneously. That is, unless some new control/mode is added to make that happen, in which case the user interface becomes more complicated.

Although, I will see if there is a way to do this in the Curve Settings dialog as you suggest. I've been known to change my mind before (hopefully for the right reasons).

@Wastus A separate issue is being worked which would allow 'partially defined' axis points - where one of the two coordinates of an axis point is not known because the horizontal and vertical axes do not meet at a well-defined intersection. So, adding a fourth axis point may or may not mean that a new coordinate system is being defined.

**Comment by Wastus** [comment]
@markummitchell Ah okay, now I understand, I think that's a good approach. Yeah I've seen that other issue (and I'd love to see a solution to it), that's why I put those parentheses to the suggestion.

Maybe adding an entry "View All" to the dropdown menu is a possible way to display everything (in that mode it might be best to disable the editing functions, because it isn't clear on which part the user is working on.

**Comment by markummitchell** [comment]
@Wastus Great suggestion for View All. And, when there is only one coordinate system, the controls involved with multiple coordinate systems could be disabled so simplify the user's interactions.

**Comment by markummitchell** [comment]
All goals were accomplished. Merged multigraph branch into master
