### ISSUE TITLE
Export broken

### ISSUE THREAD

**Issue by projekter** [markummitchell/engauge6#40]
After I exported the points to a csv (or tsv) file, only the x coordinates are given correctly, y is always given as NAN. The [problematic file](https://github.com/markummitchell/engauge6/files/52184/ErrorModel.zip) is attached. I first thought that having the axis go from 0 to 0.05 might be a problem (German Windows - possibly a comma is needed as decimal separator), but it neither works for 0 to 5.

**Comment by markummitchell** [comment]
Hello Benjamin, I've attached a fixed version of the DIG file. I had to
remove a point near x=-136.

The problem was that point was marked as the first point, according to an
'ordinal' value. This is a problem since the leftmost point was already
marked as the first point. This corruption was causing the crashes.

I will try to recreate the problem so I can fix it. Do you know which
software version you were using (in Help /  About)?

**Comment by markummitchell** [comment]
Hello Benjamin, I've attached a fixed version of the DIG file. I had to remove a point near x=-136. The problem was that point was marked as the first point, according to an 'ordinal' value. This is a problem since the leftmost point was already marked as the first point. This corruption was causing the crashes. I will try to recreate the problem so I can fix it. Do you know which software version you were using (in Help / About)?

[ErrorModel.zip](https://github.com/markummitchell/engauge6/files/53000/ErrorModel.zip)

**Comment by crayxt** [comment]
@markummitchell maybe it is a good idea to add software version info to dig files?

**Comment by projekter** [comment]
Thank you, the fixed version of this file now works.
I created the file with 6.2, but tried (only to export, not to create the file) as well with 6.1 and both failed. I used Segment Fill to create the points; as far as I remember, I did it from left to right, but I cannot promise this.

**Comment by crayxt** [comment]
@projekter so I suppose we can close this ticket now? I am still curious though how that happened

**Comment by markummitchell** [comment]
This is a hard one to solve. I'll keep trying to produce the problem, and create a new issue when I have the engauge_error_report file that appears when non-release executables create when an assert statement is triggered.
