### ISSUE TITLE
log4cpp to log4cplus migration

### ISSUE THREAD

**Issue by crayxt** [markummitchell/engauge6#61]
Could you please review the subject? log4cpp seems to be not maintained well, whereas log4cplus is updated constantly. It is much easier to build log4cplus after all.
https://github.com/log4cplus/log4cplus

**Comment by crayxt** [comment]
I meant migrate the engauge from log4cpp to log4cplus, just curious whether it is worth it.

**Comment by markummitchell** [comment]
Is the end of life for log4cpp known? It looks like log4cplus is not yet stable yet. If log4cpp can still be used until log4cplus is stable, or close to stable, across all distributions then exchanging log4cplus for log4cpp could be straightforward. Otherwise, either the code gets complicated so it can deal with incompatible APIs, or some users will be unable to build/install the software.

**Comment by crayxt** [comment]
I opened this when several attempts to build log4cpp on appveyor ci failed. Since then I built it locally and from now on using pre built archive.

**Comment by crayxt** [comment]
Ok, I've set up log4cpp on Windows, this issue no longer relevant.
