### ISSUE TITLE
How to hande weird axis?

### ISSUE THREAD

**Issue by np-8** [markummitchell/engauge6#79]
I am trying to reproduce [this](http://www.tvu.com/PNextGenTFwebFig3.jpg) graph. I scaled it first to 400%x400% to make the reproduction more accurate.

I found out that points in the axis (grid points, for example) tend to tell "wrong numbers". I drew the figure below with Inkscape. There all the colored rectangles are exactly identical in size. As you can see, the axis interval from "0 to 20" and "60 to 80" are clearly shorter than the others. 

1) How should I handle this kind graph? 

2) Also, the figure was tilted, so I rotated with Gimp. Is this neccessary? 

3) The axis calibration in Engauge uses only 3 points. Should there be an option to use more ("unlimited") points for axis calibration?

![strange_axis](https://cloud.githubusercontent.com/assets/17479683/13329722/3fbc5894-dbfe-11e5-910c-2b8e819fee1a.PNG)

**Comment by markummitchell** [comment]
I recommend stretching the image using GIMP until sections are equal. There
are discontinuities from(maybe) scanning skipping

**Comment by markummitchell** [comment]
I tried to fix your image, but was unsuccessful. I thought that the two discrepancies (0-20 and 60-80) could be fixed by making horizontal cuts and then sliding pieces up or down. However, I could see that those fixes would make the titanium line discontinuous. Another clue that my fix would not work is that the four sides of the diagram do not form a parallelogram. The left side is a little longer than the right side, reducing the parallelogram to a quadrilateral. A fundamental assumption of Engauge is that an affine transformation is involved. An affine transformation always involves a parallelogram. Some options: (1) ignore the problem and accept the slight loss in accuracy (2) get a better scan (3) try to adjust the image to fix the discrepancies. There may not be a tool that can fix the image, however, although GIMP may be a good start. 

This problem is external to Engauge.
