### ISSUE TITLE
Feature Request: Simple Curve Fitting from Identified Points

### ISSUE THREAD

**Issue by jkulesza** [markummitchell/engauge6#8]
Currently Engauge permits interpolation as a way of manipulating captured data to conform to a consistent domain (e.g., interpolate Y's at X's from all curves, interpolate Y's at X's from first curve, interpolate Y's at grid line X's).  

However, it would be useful to also provide a curve fitting algorithm using a least-squares approach to fit "simple" polynomial, logarithmic, and/or exponential models and provide basic diagnostics (e.g., R^2 values and statistics on residuals) and range of applicability (i.e., minimum and maximum domain considered).

**Comment by markummitchell** [comment]
I can think of two issues here, and wanted to see if they capture your thoughts.

1) "Spline- instead of linear-interpolation between points". A spline curve could be drawn through points when adding points, instead of simple straight line segments. Then during export, points could be sprinkled along the spline using an algorithm that never lets the exported line segments deviate from the spline by more than some epsilon. Advantages - fewer points needed during digitizin of smooth curves, probably with better accuracy. Disadvantages - a pain to deal with splines at sharp corners in the curve.

2) "Numeric analysis". If the user knows the curve follows something like y=a2*x^2 + a1*x + a0, then it would be nice for the software to determine a0, a1 and a2, along with some measurement of the quality of fit. This could be done as the user adds points, to provide immediate feedback. What would you think about doing this analysis in a tool like R or Matlab? Engauge can send the data to that tool using shared memory or some other method.

**Comment by nattomi** [comment]
While it's nice to have some options for interpolation, I also support the idea that Engauge must be kept as simplistic as possible and be used only for obtaining raw coordinates and leaving interpolation to external applications as @markummitchell suggested! To achieve this, it would be more important to be able to export pointsets into one of the well-supported (preferably binary) data formats such as netCDF.

**Comment by jkulesza** [comment]
Thanks for the *quick* replies!  

@markummitchell, I like both of those ideas.  As an engineer, I prefer what you call numeric analysis which would let a user fit up to an arbitrary order polynomial or other common function like a log, exponential, etc. and provide feedback on the quality of fit (I'd propose something simple like R^2 value, maximum and minimum residual values (absolute and percentage), mean and 1-sigma residual values - five metrics).  With this approach, a user has not only extracted the data of interest but also now has an analytic model that might be used elsewhere.  It would be *outstanding* if this could be performed in real-time (perhaps even overlaying the model plot on the original?).  

I also like the idea of spline (either cubic and/or Bézier) fitting as an alternative; however, those fits I would really want to have overlaid on the original plot because the user will be selecting relatively few points to achieve the fit (to prevent [overfitting](http://en.wikipedia.org/wiki/Overfitting)) and must know when "enough is enough."  For this type of spline fitting (particularly Bézier), it would be very helpful to be able to click-and-drag the control points in the graph.

Regarding use of an external tool, I would prefer to have this functionality, to a simple degree at least, in Engauge.  I recently used Engauge to remaster a plot (from 1944!) and used Mathematica to develop my fit.  I don't mind using an external tool; however, the entire time I was wishing I could keep everything in one environment to prevent moving data around, storing additional files, etc. for a relatively simple set of three fits.  Of course, if I determined Engauge didn't have the functionality I wanted, I'd roll over to my external tool of choice and cope with the additional burden.  However, I suspect that for most users the inclusion of fitting in Engauge will save them the burden of acquiring/learning/maintaining another software package to perform a relatively straightforward operation.

I would be cautious about sending data other than through a concrete format (i.e., a file).  In the world of engineering quality assurance, it's much easier to track and archive a file (using a checksum) than the pass through memory.  This also alleviates the need to have both the sender (Engauge) and receiver (e.g., R) put through the same software verification and validation - they are no longer strongly linked).  Finally, it prevents the need to maintain those links to other applications as they evolve.

@nattomi, I agree that Engauge should be kept simple; however, if it is already performing interpolation of data, adding fitting is a natural and logical progression.  I also agree that additional file formats would be helpful; however, I see a couple disadvantages:

1. While binary is nice, ASCII is truly universal and easily interrogated (by human and computer).  I'm curious about how large of datasets are being created with Engauge that binary would offer significant advantages over ASCII.
2. What file formats make the list for inclusion?  How are they selected?  How are they supported as the formats evolve?  I'm fearful of having lots of libraries needed by Engauge to support everyone's favorite binary format when in the end we're dealing with simple x-y point data.

**Comment by jkulesza** [comment]
Sorry - misclick.

**Comment by nattomi** [comment]
@jkulesza, let me share my experiences about the size of possible datasets. My team has digitized so far more than 20000 images using Engauge 4 (have a look at http://geodata.ggki.hu/tellurics/doc/bigdata2014NT.pdf for more info). All my digitized data is in PostreSQL now. I queried the database for the image with the largest number of points and it turned out that this number is 9034. In Engauge 4 and 5 you need 24 bytes to store pixel coordinates and user coordinates associated to a point. So storing this is about 200KB which I think is quite comparable to what it would take when stored as ASCII. So no great advantage in terms of storage. However, I'm convinced that loading the binary into any application is faster. Quite often I have to do some kind of batch processing on those 20000 files, this is clearly an example of a case when the speed of file io operations becomes a critical point.

I agree with you that there isn't any format which conforms everyone's need. Actually, as I mentioned above the file format Engauge5 uses is already binary, so it's almost perfect for my purposes, but... this format contains not just the data points but also information about the session too (plus the original image). So, to summarize what I would like to say: the emphasis is more on using a format for storing data which handles pointsets and session information separately. But I think we are getting off-topic now so it would be better to open a separate issue for file formats. Last time I compiled EG6 I saw that @markummitchell introduced some sort of xml based structure.

**Comment by jkulesza** [comment]
@nattomi Excellent, thank you for sharing your experiences and that very interesting presentation.  It is great to see how other folks use this tool (as I am quite new to it, but am so far *very* impressed).

I agree, it would be good to open a new issue to discuss file formats - it will be interesting to see what is discussed.

**Comment by markummitchell** [comment]
Good suggestions. After some research, I learned the following:

1) One way to provide curve fitting inside Engauge is to provide Python scripting using PyQt or similar. This could work like Visual Basic in Excel - with the complexity hidden away from non-power users. Whenever a curve point changed, the curve would be sent to the script. Output, like curve fitting goodness of fit, could be to an initially-invisible window. This approach would make development much easier and shorter (by months), and keep the GUI simple.

2) Instead of python scripting, Engauge could pretty easily send information through sockets and/or an SQL database to external tools (publish/subscribe). Again, the GUI stays simple.

In either case, a nice trick is to provide skeleton code that people can use as the starting point for their own custom solutions. I've implemented both solutions in various applications, and can vouch for them.

Your thoughts?

**Comment by LiaungYip** [comment]
I like Python, so I'm voting for that.

**Comment by jkulesza** [comment]
@markummitchell, thanks for doing the research on this.  Of the two approaches you outlined, I much prefer interfacing with Python which would allow the complexity to be hidden for most users but accessed and customized by power users.  As you noted, providing skeleton code which provides basic functionality which would be expanded upon would be excellent.

The only concern I have with this approach is introducing another dependency.  Perhaps this could be handled with a compile-time flag to enable/disable the code (and thus require/ignore the dependency)?  

This would keep this side of the development easier and shorter (as you described) and still permit the functionality.  Perhaps later, some subset of the functionality could be coded natively to avoid the dependency and still provide users some functionality where the user could opt (at compile time) whether to use the native fitting or Python-based fitting (presumably more flexible but with more dependency overhead).

**Comment by nattomi** [comment]
Another way to keep the GUI simple is to ship the more complex functionalities in form of plugins. Users could decide whether they do a minimal installation or let's say a full installation with all possible plugins available. I support the Python-scripting idea as well. Many applications like GIMP, Quantum GIS (which is Qt) offers such possibility.

**Comment by markummitchell** [comment]
Each curve can be drawn with straight line segments, or with fitted curves. The fitted curves are nice since smooth curves can be accurately tracked with fewer points.

Deployment of python scripting across all platforms looked to be a lot of work, and not worth the effort.

**Comment by jkulesza** [comment]
@markummitchell Outstanding, thanks for the hard work to implement this (and your work on engauge, in general)!
