### ISSUE TITLE
Export File Formats

### ISSUE THREAD

**Issue by markummitchell** [markummitchell/engauge6#9]
Some file formats that may be good for export, in addition to csv/tsv spreadsheet formats that will be implemented very soon, and the xml that is already output...

1) NetCDF is a powerful, and well supported, binary format. There may be issues with standards in Windows. Probably easy to add to Engauge, although I feel sorry for the downstream developers.

2) SQL database tables. Very easy to add to do the actual writing to the tables, but providing flexibility in terms of tables names, and especially table structures, would complicate things.

**Comment by jkulesza** [comment]
For NetCDF, unless someone is clamoring for the functionality, perhaps this is something to defer until later since the current export format(s) are serviceable as-is.

For SQL, can the export dialog be made flexible enough to take key parameters assuming a fixed structure?  This way, someone's DB could include a table for Engauge exported data that has a schema defined by Engauge.  The SQL commands exported by Engauge would then need relatively little customization (through the Export dialog, or failing that, post-export) to permit those commands to act upon the correct DB/table to load the new data.

For the current ASCII export, could another option be added where it does not put all "x's" into the first column, but rather groups data sets together.  Sorry for the poor articulation, and it's hard to show with a snippet, but the ultimate objective is to have this:
```
Domain A, Range A, Domain B, Range B, Domain C, Range C
xa1, ya1, xb1, yb1, xc1, yc1
```
rather than
```
Domain, Range A, Range B, Range C
xa1, ya1 ,     ,
xb1,     , yb1 ,
xc1,     ,     , yc1
```
where the length of the ```xa1/ya1``` ordered pair vector may be a different length than ```xb1/yb1``` or ```xc1/yc1``` but each domain/range value is guaranteed to have a paired value.

**Comment by markummitchell** [comment]
Yes, there must be some flexibility in the SQL to support arbitrary table and field names. Some mapping of Engauge field to SQL field. Also, an option to clear out the table(s) whenever the data is refreshed. This complexity would be hidden from users who were not interested in SQL export.

I don't understand how the xa1, xb1 and xc1 could be on the same line unless ya1=yb1=yc1. And if that was the case, then I would suggest inverting the graph. I will think about this some which may clear up my confusion.

**Comment by jkulesza** [comment]
@markummitchell, Please let me provide a concrete example of what I mean for how to segregate the CSV file.  Sorry for not thinking/taking the time to do this before.  This example was exported with *Raw X's and Y's* (the only way to ensure the data file contains strictly user-defined points) with spaces added for clarity:
```
x,        Curve1,   Curve2,   Curve3
0.242966, 0.375076, ,
0.656811, 2.24111,  ,
1.16166,  4.4479,   ,
1.52428,  5.70298,  ,
1.84899,  7.37213,  ,
2.15042,  8.91564,  ,
2.20748,  9.97618,  ,
3.51137,  ,         0.375777,
3.89844,  ,         1.84642,
4.34373,  ,         4.46751,
4.7357,   ,         6.3158,
5.0376,   ,         7.89528,
5.36371,  ,         9.67233,
6.95245,  ,         ,         0.338643
7.57835,  ,         ,         3.53333
8.02902,  ,         ,         6.56803
8.78314,  ,         ,         9.63543                                                                         
```
where what I would like to have available is:
```
x1,       Curve1,   x2,      Curve2,   x3,      Curve3
0.242966, 0.375076, 3.51137, 0.375777, 6.95245, 0.338643
0.656811, 2.24111,  3.89844, 1.84642,  7.57835, 3.53333
1.16166,  4.4479,   4.34373, 4.46751,  8.02902, 6.56803
1.52428,  5.70298,  4.7357,  6.3158,   8.78314, 9.63543
1.84899,  7.37213,  5.0376,  7.89528,         ,
2.15042,  8.91564,  5.36371, 9.67233,         ,
2.20748,  9.97618,         ,        ,         ,
```
With this format, I can tell a plotting program "plot columns 1,2" or "plot columns 5,6" and *know* that for every value in columns 1/3/5 there will be a corresponding, un-interpolated, user-defined value in columns 2/4/6.

This output is comparable to what one might get if he or she uses the Linux ```paste``` command to concatenate columns of paired data points together.

**Comment by nattomi** [comment]
netCDF: works for me!
SQL: just an idea: how about storing pointsets into an SQLite database? it's a single file, therefore it could even be used as a complete replacement of the former .dig project files. SQLite is also widely supported. Nothing offers greater flexibility in terms of extracting custom data of interest than writing SQL queries. For the not-so-power users, there could be a possibility to load some predefined queries which produces formats such as the one suggested by @jkulesza. A Quantum GIS-like query editor window can be also implemented (see https://woostuff.files.wordpress.com/2010/12/q.png?w=628).

Me personally won't even need any export format, if the pixmap that serves as a basis for the digitization wouldn't be encoded into the project file (as it was done in Engauge 5). This a complication because if a pixmap to be digitized is large in size then the resulting project file becomes large as well which makes it very difficult to exchange (again, it's not a problem with a single file but I'm talking about mass processing of files now).

**Comment by markummitchell** [comment]
For now, let's see if the simpler approach of providing starting-point python scripts will satisfy any need to export in other formats. In other words, users can modify the ExampleParseDig.py script to save into SQL tables, for example.This approach keeps the Engauge GUI simple.
